import random


def hangman():
    words = ['point', 'fork', 'abject', 'oafish', 'savory', 'smile', 'desert', 'lopsided', 'join', 'thrill', 'acoustic',
             'design', 'shaggy', 'summer', 'frogs', 'soap', 'gigantic', 'lighten', 'toes', 'actor', 'tremble',
             'unwieldy', 'zinc', 'claim', 'lie', 'same', 'hungry', 'blink', 'pets', 'tiny', 'twig', 'wide-eyed',
             'amused', 'doubt', 'explode', 'coat', 'second', 'skirt', 'wealthy', 'jelly', 'stream', 'vessel',
             'discovery', 'grieving', 'wood', 'paper', 'incredible', 'yarn', 'available', 'kill', 'spot', 'bury',
             'trousers', 'grubby', 'gun', 'stingy', 'nose', 'squash', 'carpenter', 'selection', 'anger', 'addicted',
             'steady', 'strong', 'tall', 'care', 'sticky', 'moaning', 'owe', 'butter', 'instrument', 'testy', 'brash',
             'hanging', 'miss', 'cowardly', 'shame', 'adjustment', 'fetch', 'puzzling', 'outrageous', 'group',
             'vacation', 'ducks', 'tongue', 'window', 'program', 'tasty', 'shrill', 'connect', 'rest', 'form',
             'adhesive', 'potato', 'enjoy', 'flagrant', 'pull', 'foot', 'reach', 'hair', 'eatable', 'wave', 'tacky',
             'envious', 'creepy', 'brown', 'secret', 'disgusting', 'giants', 'apparel', 'attempt', 'silk', 'dress',
             'double', 'insect', 'unsightly', 'snails', 'ladybug', 'rambunctious', 'unwritten', 'harsh', 'battle',
             'whine', 'unusual', 'phone', 'glistening', 'sneeze', 'scorch', 'sassy', 'introduce', 'airport', 'bait',
             'puffy', 'borrow', 'wonderful', 'class', 'crawl', 'writer', 'fold', 'productive', 'lean', 'receive',
             'attend', 'veil', 'rock', 'jump', 'sack', 'scribble', 'greasy', 'damaging', 'wild', 'absurd', 'jeans',
             'glib', 'respect', 'illustrious', 'ship', 'balance', 'physical', 'youthful', 'money', 'caption', 'trust',
             'axiomatic', 'ajar', 'flag', 'excellent', 'snow', 'hissing', 'bed', 'statement', 'flock', 'suit', 'number',
             'holiday', 'thick', 'groan', 'lyrical', 'fluffy', 'playground', 'wheel', 'compete', 'school', 'cabbage',
             'fretful', 'provide', 'likeable', 'depend', 'fixed', 'quixotic', 'wasteful', 'condemned', 'vegetable',
             'wind', 'admit', 'knotty', 'nail', 'spray', 'deer', 'dangerous', 'income', 'familiar', 'telephone', 'pump',
             'act', 'car', 'division', 'little', 'tasteful', 'useless', 'volatile', 'alleged', 'odd', 'thread',
             'vivacious', 'cheer', 'desk', 'hospital', 'prose', 'agreement', 'letter', 'tip', 'reflective', 'learn',
             'fairies', 'magic', 'office', 'hum', 'substance', 'position', 'conscious', 'produce', 'wrap', 'scary',
             'cars', 'button', 'weather', 'immense', 'mine', 'periodic', 'chew', 'toe', 'grandfather', 'inform',
             'uptight', 'press', 'trite', 'force', 'sponge', 'grouchy', 'beds', 'spoil', 'pencil', 'unhealthy',
             'behavior', 'assorted', 'deafening', 'fact', 'legs', 'pleasure', 'better', 'woozy', 'questionable', 'bomb',
             'lick', 'throat', 'pipe', 'home', 'happy', 'angry', 'earthy', 'rely', 'clover', 'letters', 'field',
             'amuse', 'territory', 'zoo', 'tan', 'skate', 'cup', 'watch', 'burn', 'marble', 'zippy', 'calendar', 'rub',
             'cynical', 'linen', 'cycle', 'normal', 'male', 'bright', 'sprout', 'harass', 'dramatic', 'calculating',
             'dare', 'theory', 'ask', 'dinosaurs', 'roof', 'remove', 'sparkle', 'aberrant', 'open', 'shock', 'trains',
             'move', 'mark', 'ban', 'late', 'scissors', 'eight', 'ticket', 'slippery', 'soft', 'employ', 'use',
             'smelly', 'white', 'half', 'fit', 'nice', 'return', 'punch', 'snail', 'pretend', 'deep', 'brick', 'settle',
             'afford', 'bumpy', 'handle', 'hop', 'rush', 'elderly', 'bawdy', 'eyes', 'cattle', 'glossy', 'detailed',
             'scene', 'underwear', 'adamant', 'cooing', 'selective', 'knock', 'bike', 'null', 'delicate', 'signal',
             'attraction', 'coordinated', 'authority', 'governor', 'oil', 'passenger', 'children', 'hypnotic',
             'education', 'ethereal', 'interfere', 'boorish', 'towering', 'bore', 'wobble', 'smoggy', 'existence',
             'sudden', 'frightened', 'engine', 'dog', 'cakes', 'neck', 'volcano', 'frail', 'scatter', 'examine',
             'exultant', 'elated', 'jog', 'dull', 'alert', 'occur', 'unkempt', 'quince', 'wacky', 'please', 'jellyfish',
             'edge', 'imaginary', 'sturdy', 'warlike', 'abounding', 'meaty', 'reward', 'romantic', 'harbor', 'permit',
             'overrated', 'melted', 'manage', 'stop', 'chickens', 'fragile', 'brush', 'toy', 'minor', 'round',
             'concern', 'rat', 'scientific', 'dad', 'sour', 'devilish', 'stick', 'idea', 'spurious', 'poison', 'cute',
             'medical', 'gabby', 'transport', 'wall', 'waiting', 'jumbled', 'scrape', 'synonymous', 'annoyed', 'lucky',
             'mourn', 'harmonious', 'secretive', 'festive', 'weak', 'inexpensive', 'nosy', 'perfect', 'parched',
             'premium', 'clumsy', 'mountainous', 'slave', 'writing', 'internal', 'women', 'exuberant', 'shake', 'ruin',
             'visit', 'daffy', 'tangible', 'iron', 'identify', 'solid', 'sulky', 'cast', 'absent', 'bee', 'van', 'day',
             'prickly', 'thankful', 'loutish', 'receipt', 'cheap', 'shivering', 'deserve', 'succeed', 'experience',
             'sick', 'educate', 'magnificent', 'horrible', 'muddled', 'ball', 'trucks', 'hysterical', 'wash', 'elbow',
             'sense', 'hammer', 'hill', 'vagabond', 'screw', 'development', 'noxious', 'homely', 'enchanting',
             'appliance', 'obey', 'pack', 'person', 'spoon', 'sedate', 'holistic', 'grate', 'incompetent', 'standing',
             'explain', 'rude', 'evanescent', 'flight', 'chief', 'nippy', 'wry', 'base', 'haunt', 'bite', 'aspiring',
             'plug', 'average', 'spicy', 'bat', 'work', 'blush', 'therapeutic', 'straw', 'friends', 'slow', 'change',
             'spring', 'decorous', 'welcome', 'knowledge', 'hug', 'hobbies', 'political', 'garrulous', 'obeisant',
             'telling', 'rich', 'general', 'listen', 'permissible', 'broad', 'lonely', 'stereotyped', 'ray',
             'encouraging', 'fireman', 'bored', 'earsplitting', 'improve', 'seal', 'ceaseless', 'agree', 'spiffy',
             'seat', 'nasty', 'zip', 'power', 'numberless', 'painful', 'replace', 'insurance', 'cows', 'irritate',
             'boundary', 'frightening', 'powerful', 'cloudy', 'grass', 'keen', 'hate', 'annoying', 'race', 'creator',
             'pinch', 'attract', 'page', 'macho', 'rod', 'tie', 'overwrought', 'polish', 'stiff', 'past', 'lazy',
             'broken', 'tense', 'warm', 'feeble', 'thirsty', 'skinny', 'sloppy', 'contain', 'goofy', 'charge',
             'callous', 'wrench', 'drain', 'influence', 'share', 'well-off', 'economic', 'locket', 'voracious',
             'distribution', 'discover', 'exist', 'peaceful', 'reply', 'flimsy', 'scrawny', 'second-hand', 'connection',
             'cake', 'hand', 'scent', 'draconian', 'itch', 'hunt', 'mellow', 'young', 'idiotic', 'rampant', 'things',
             'comfortable', 'addition', 'remarkable', 'unaccountable', 'squeak', 'drag', 'determined', 'paddle',
             'undesirable', 'fine', 'screeching', 'farm', 'clean', 'wren', 'cold', 'squeeze', 'match', 'oranges',
             'parallel', 'witty', 'own', 'tightfisted', 'nostalgic', 'faithful', 'clam', 'few', 'bloody', 'shop',
             'guarded', 'part', 'panicky', 'year', 'release', 'childlike', 'puncture', 'grumpy', 'gate', 'first', 'ink',
             'full', 'continue', 'low', 'gentle', 'rhetorical', 'amusement', 'cheat', 'debonair', 'waves', 'stain',
             'attach', 'silky', 'confess', 'swim', 'boiling', 'perform', 'food', 'blue-eyed', 'thaw', 'floor',
             'promise', 'scare', 'notebook', 'reaction', 'industry', 'classy', 'small', 'war', 'fluttering', 'healthy',
             'horses', 'whispering', 'sister', 'mature', 'macabre', 'hole', 'last', 'flap', 'even', 'announce', 'songs',
             'obsequious', 'scarf', 'preach', 'panoramic', 'unit', 'groovy', 'cuddly', 'rabbit', 'shape', 'collar',
             'quirky', 'royal', 'found', 'cloistered', 'ignore', 'melt', 'repeat', 'river', 'measure', 'wet', 'pet',
             'illegal', 'pumped', 'appear', 'poor', 'phobic', 'present', 'tendency', 'plants', 'divide', 'porter',
             'straight', 'bridge', 'ludicrous', 'pastoral', 'rob', 'honey', 'ocean', 'flow', 'pigs', 'evasive', 'pine',
             'guide', 'wonder', 'blot', 'crazy', 'flashy', 'yak', 'ratty', 'bedroom', 'argue', 'utter', 'abrasive',
             'sweater', 'self', 'lamp', 'side', 'colorful', 'crowd', 'terrify', 'quick', 'spotted', 'horse',
             'motionless', 'temporary', 'badge', 'regular', 'unused', 'furry', 'juice', 'carriage', 'toothsome',
             'successful', 'cart', 'laugh', 'gusty', 'mammoth', 'lethal', 'long-term', 'aboard', 'cent', 'sable',
             'lamentable', 'reduce', 'approval', 'nutritious', 'petite', 'smiling', 'voiceless', 'mysterious',
             'utopian', 'literate', 'smoke', 'snobbish', 'closed', 'committee', 'fearful', 'incandescent', 'supreme',
             'thundering', 'divergent', 'creature', 'tremendous', 'knowing', 'stew', 'lewd', 'vest', 'memorize', 'head',
             'earth', 'obedient', 'stitch', 'dogs', 'rail', 'remember', 'property', 'applaud', 'mitten', 'symptomatic',
             'breathe', 'enthusiastic', 'sip', 'miscreant', 'watery', 'gaudy', 'succinct', 'disturbed', 'simplistic',
             'accessible', 'tawdry', 'malicious', 'title', 'train', 'request', 'crush', 'reproduce', 'instruct',
             'teaching', 'handy', 'rapid', 'price', 'blade', 'railway', 'dime', 'itchy', 'unadvised', 'stroke', 'end',
             'greedy', 'tearful', 'womanly', 'rainy', 'punishment', 'nimble', 'sky', 'waggish', 'ill-fated', 'pancake',
             'wool', 'hall', 'direful', 'need', 'blow', 'dirt', 'soggy', 'frequent', 'chalk', 'luxuriant', 'charming',
             'tin', 'expensive', 'bit', 'birthday', 'grandiose', 'tray', 'historical', 'aggressive', 'queue', 'ancient',
             'natural', 'kindly', 'disarm', 'servant', 'furniture', 'dynamic', 'necessary', 'observant', 'bikes',
             'society', 'live', 'invent', 'peace', 'health', 'like', 'fantastic', 'chubby', 'morning', 'kneel', 'thumb',
             'imagine', 'sheet', 'scared', 'vanish', 'billowy', 'lackadaisical', 'mixed', 'best', 'expand', 'look',
             'befitting', 'left', 'shoes', 'wriggle', 'marry', 'woebegone', 'terrific', 'laughable', 'honorable',
             'distinct', 'pot', 'birth', 'picayune', 'learned', 'tour', 'intend', 'fertile', 'dispensable', 'enchanted',
             'jam', 'cat', 'fast', 'craven', 'circle', 'invincible', 'scarce', 'raspy', 'buzz', 'painstaking',
             'troubled', 'short', 'superb', 'tomatoes', 'quack', 'ear', 'adjoining', 'neighborly', 'men', 'needle',
             'early', 'bubble', 'pen', 'recognise', 'land', 'pail', 'maid', 'silent', 'deranged', 'busy', 'flawless',
             'quaint', 'suppose', 'substantial', 'stretch', 'woman', 'worry', 'wound', 'wooden', 'feeling', 'stir',
             'airplane', 'close', 'rustic', 'plantation', 'cellar', 'tender', 'adorable', 'rake', 'nauseating',
             'basketball', 'bushes', 'bulb', 'kitty', 'wrist', 'simple', 'notice', 'inject', 'functional', 'super',
             'snore', 'wing', 'stare', 'private', 'guttural', 'direction', 'tub', 'fancy', 'leather', 'nine', 'brave',
             'slip', 'advise', 'pear', 'guiltless', 'chemical', 'deadpan', 'instinctive', 'five', 'building', 'profit',
             'industrious', 'free', 'strengthen', 'cut', 'special', 'room', 'loose', 'bake', 'icicle', 'snatch',
             'blushing', 'trouble', 'crime', 'behave', 'haircut', 'coach', 'valuable', 'tangy', 'alluring', 'party',
             'book', 'mushy', 'fool', 'faded', 'plant', 'whirl', 'club', 'habitual', 'paste', 'carve', 'four',
             'wrathful', 'unfasten', 'blue', 'irate', 'puzzled', 'cave', 'foolish', 'air', 'flash', 'crate', 'vague',
             'preserve', 'treat', 'light', 'tidy', 'brass', 'rescue', 'calm', 'flaky', 'quarter', 'plucky', 'advice',
             'report', 'jewel', 'poised', 'glamorous', 'mean', 'current', 'line', 'wary', 'camp', 'aboriginal', 'bead',
             'erratic', 'ignorant', 'show', 'satisfy', 'liquid', 'typical', 'cheese', 'blind', 'bite-sized', 'try',
             'vulgar', 'metal', 'matter', 'ready', 'living', 'drown', 'hope', 'tail', 'godly', 'steep', 'fierce',
             'stimulating', 'cool', 'measly', 'glove', 'dance', 'trace', 'humorous', 'lake', 'thank', 'lip', 'damaged',
             'concerned', 'toad', 'week', 'crack', 'dear', 'skin', 'resolute', 'print', 'seemly', 'detail', 'spiders',
             'impress', 'tramp', 'motion', 'confused', 'bear', 'grip', 'unite', 'slap', 'foamy', 'racial', 'frantic',
             'heal', 'scratch', 'quickest', 'judge', 'nondescript', 'married', 'file', 'cushion', 'ill-informed',
             'disillusioned', 'girl', 'peep', 'excuse', 'thoughtless', 'bolt', 'careful', 'heavenly', 'pleasant',
             'old-fashioned', 'venomous', 'zany', 'egg', 'robust', 'lock', 'well-groomed', 'sincere', 'crib', 'tiger',
             'square', 'plausible', 'meeting', 'zebra', 'consist', 'gruesome', 'rhythm', 'weight', 'squalid', 'meek',
             'faint', 'hard', 'ugliest', 'amount', 'thin', 'chivalrous', 'calculator', 'remain', 'support', 'icky',
             'spiritual', 'earthquake', 'sand', 'boy', 'knee', 'naive', 'apathetic', 'rain', 'gaping', 'scale',
             'protest', 'cheerful', 'fallacious', 'cap', 'domineering', 'lacking', 'sharp', 'effect', 'unpack', 'rare',
             'suggestion', 'count', 'rule', 'achiever', 'wreck', 'save', 'anxious', 'ragged', 'bang', 'breakable',
             'birds', 'robin', 'fence', 'new', 'longing', 'subsequent', 'cemetery', 'card', 'blood', 'real', 'pretty',
             'rightful', 'freezing', 'carry', 'scattered', 'alike', 'jail', 'massive', 'oceanic', 'riddle', 'sleepy',
             'roll', 'example', 'curly', 'abaft', 'protect', 'uttermost', 'scream', 'imperfect', 'educated',
             'understood', 'friendly', 'adaptable', 'name', 'comb', 'annoy', 'tick', 'mask', 'reign', 'superficial',
             'coast', 'exercise', 'volleyball', 'sun', 'animal', 'stupendous', 'discreet', 'books', 'girls', 'one',
             'salt', 'taboo', 'bad', 'jittery', 'yam', 'search', 'fry', 'reflect', 'mug', 'decisive', 'wine', 'trashy',
             'spell', 'basket', 'coil', 'science', 'copy', 'repair', 'uncovered', 'unsuitable', 'abandoned', 'stem',
             'forgetful', 'right', 'growth', 'basin', 'grateful', 'hurried', 'swanky', 'embarrass', 'fang', 'animated',
             'joke', 'cure', 'expert', 'lumber', 'psychotic', 'abhorrent', 'nervous', 'gather', 'separate', 'untidy',
             'pocket', 'gifted', 'abiding', 'purple', 'purpose', 'complete', 'probable', 'cannon', 'cherry', 'rings',
             'tap', 'moan', 'sail', 'death', 'obnoxious', 'acidic', 'tank', 'offend', 'love', 'church', 'awake',
             'partner', 'sofa', 'dock', 'shade', 'curved', 'rainstorm', 'polite', 'invite', 'mouth', 'stage', 'planes',
             'scintillating', 'obsolete', 'coherent', 'winter', 'destroy', 'glorious', 'toothpaste', 'ubiquitous',
             'auspicious', 'giant', 'easy', 'pizzas', 'old', 'accidental', 'tight', 'sticks', 'stranger', 'sordid',
             'pale', 'noiseless', 'lush', 'reading', 'rot', 'yell', 'curvy', 'gleaming', 'melodic', 'attack', 'cover',
             'copper', 'erect', 'perpetual', 'rural', 'pop', 'ski', 'unnatural', 'breezy', 'question', 'languid',
             'fearless', 'empty', 'cultured', 'yielding', 'spectacular', 'finicky', 'alive', 'deserted', 'subtract',
             'flowery', 'abrupt', 'dolls', 'fasten', 'dark', 'wicked', 'leg', 'concentrate', 'public', 'futuristic',
             'sparkling', 'accept', 'brainy', 'exotic', 'acid', 'dusty', 'well-to-do', 'trick', 'twist', 'strap',
             'good', 'proud', 'poke', 'unequal', 'innate', 'tiresome', 'thinkable', 'representative', 'cracker', 'tire',
             'sheep', 'brake', 'relax', 'imported', 'mint', 'trap', 'mess up', 'neat', 'unlock', 'strip', 'suffer',
             'prepare', 'ants', 'mass', 'nod', 'courageous', 'thing', 'limping', 'check', 'value', 'nest',
             'efficacious', 'handsomely', 'legal', 'astonishing', 'flower', 'minister', 'wander', 'describe', 'lavish',
             'weary', 'vast', 'crow', 'curve', 'descriptive', 'island', 'diligent', 'aftermath', 'drink', 'hellish',
             'many', 'thunder', 'steadfast', 'muddle', 'disapprove', 'marvelous', 'voice', 'yoke', 'absorbing',
             'arrogant', 'nonstop', 'shave', 'interesting', 'silly', 'geese', 'upset', 'reject', 'accurate', 'gaze',
             'lunchroom', 'account', 'walk', 'two', 'far-flung', 'messy', 'serious', 'pat', 'vigorous', 'play', 'chase',
             'quarrelsome', 'able', 'back', 'frog', 'type', 'feigned', 'belong', 'murky', 'memory', 'wax', 'time',
             'organic', 'bells', 'crash', 'worthless', 'excited', 'onerous', 'control', 'art', 'payment', 'glass',
             'punish', 'object', 'fabulous', 'advertisement', 'debt', 'hesitant', 'nebulous', 'yawn', 'difficult',
             'cactus', 'oven', 'cook', 'cry', 'street', 'merciful', 'yummy', 'innocent', 'stale', 'slope', 'turn',
             'amuck', 'suspend', 'abortive', 'load', 'elite', 'precious', 'squirrel', 'trip', 'dislike', 'license',
             'bent', 'bag', 'whimsical', 'fix', 'aromatic', 'useful', 'celery', 'pointless', 'note', 'ruddy', 'grin',
             'man', 'encourage', 'string', 'horn', 'numerous', 'bow', 'spade', 'glow', 'wrong', 'teeny-tiny',
             'wretched', 'oval', 'excite', 'nutty', 'boast', 'actually', 'wish', 'truck', 'rice', 'acceptable', 'allow',
             'caring', 'record', 'loud', 'kettle', 'moon', 'machine', 'different', 'wanting', 'fresh', 'abnormal',
             'giddy', 'hot', 'answer', 'protective', 'camera', 'sea', 'exchange', 'destruction', 'sneaky', 'observe',
             'taste', 'statuesque', 'demonic', 'distance', 'obtainable', 'beginner', 'slim', 'overt', 'chance', 'noise',
             'zealous', 'daughter', 'compare', 'risk', 'materialistic', 'energetic', 'murder', 'acrid', 'swing',
             'maddening', 'curl', 'doctor', 'teeth', 'unbiased', 'comparison', 'happen', 'wait', 'mighty', 'action',
             'fly', 'quill', 'nifty', 'fascinated', 'entertain', 'trail', 'husky', 'enormous', 'flood', 'resonant',
             'stay', 'abashed', 'disastrous', 'momentous', 'story', 'dirty', 'pie', 'can', 'religion', 'tow', 'tenuous',
             'equable', 'maniacal', 'whistle', 'jobless', 'radiate', 'clear', 'clap', 'chop', 'mix', 'stomach', 'cream',
             'structure', 'delight', 'cagey', 'library', 'afraid', 'extend', 'ashamed', 'lying', 'plate', 'paint',
             'unarmed', 'long', 'relation', 'extra-small', 'damage', 'brawny', 'capable', 'wide', 'rotten', 'spy',
             'nerve', 'swift', 'repulsive', 'amazing', 'purring', 'magical', 'stamp', 'moor', 'fish', 'unable', 'north',
             'warn', 'mind', 'versed', 'fog', 'hands', 'shirt', 'well-made', 'relieved', 'gamy', 'label',
             'disagreeable', 'zoom', 'dead', 'recess', 'marked', 'hat', 'pickle', 'donkey', 'roomy', 'hulking',
             'agonizing', 'drop', 'fruit', 'uppity', 'weigh', 'milk', 'efficient', 'park', 'nut', 'barbarous', 'want',
             'combative', 'used', 'discussion', 'knife', 'talented', 'sweltering', 'teeny', 'selfish', 'wiry', 'size',
             'sore', 'aback', 'apparatus', 'offer', 'admire', 'needy', 'changeable', 'large', 'ahead', 'rate',
             'defective', 'enter', 'expect', 'plane', 'pan', 'fowl', 'tumble', 'smooth', 'sidewalk', 'downtown',
             'yellow', 'jealous', 'raise', 'sort', 'squeal', 'green', 'knot', 'pricey', 'stone', 'fortunate', 'sound',
             'spooky', 'disagree', 'worm', 'spare', 'increase', 'burly', 'rabbits', 'ablaze', 'loving', 'develop',
             'alcoholic', 'muscle', 'country', 'fall', 'fumbling', 'wakeful', 'decorate', 'ice', 'violet', 'crooked',
             'huge', 'gratis', 'next', 'soothe', 'kiss', 'orange', 'juvenile', 'space', 'system', 'face', 'scold',
             'defeated', 'snotty', 'safe', 'drawer', 'skillful', 'spark', 'wilderness', 'ritzy', 'expansion',
             'truculent', 'plough', 'help', 'careless', 'ordinary', 'cooperative', 'lively', 'obtain', 'desire', 'eye',
             'trees', 'curtain', 'spotty', 'plan', 'zonked', 'stormy', 'practice', 'whip', 'bare', 'near', 'stuff',
             'daily', 'cough', 'penitent', 'color', 'seed', 'friction', 'son', 'humor', 'juicy', 'limit', 'tame',
             'aware', 'halting', 'prefer', 'flame', 'analyze', 'fade', 'hapless', 'awful', 'suggest', 'wealth', 'delay',
             'narrow', 'obscene', 'grandmother', 'unbecoming', 'place', 'naughty', 'disgusted', 'arm', 'abundant',
             'fax', 'visitor', 'powder', 'pies', 'hurry', 'grain', 'highfalutin', 'lumpy', 'agreeable', 'texture',
             'whole', 'crown', 'meddle', 'infamous', 'tasteless', 'minute', 'deceive', 'treatment', 'add', 'bashful',
             'heat', 'didactic', 'cruel', 'refuse', 'amusing', 'deeply', 'verse', 'material', 'store', 'zipper', 'tree',
             'burst', 'spiteful', 'verdant', 'tug', 'houses', 'decay', 'ripe', 'cautious', 'surround', 'threatening',
             'ground', 'bouncy', 'hushed', 'parcel', 'finger', 'recondite', 'subdued', 'vein', 'modern', 'breath',
             'thought', 'frighten', 'challenge', 'tacit', 'embarrassed', 'level', 'apologise', 'capricious', 'bell',
             'cumbersome', 'imminent', 'injure', 'high-pitched', 'obese', 'wandering', 'tired', 'film', 'peel',
             'impolite', 'drab', 'hydrant', 'smell', 'entertaining', 'windy', 'pause', 'sin', 'jaded', 'dam', 'grade',
             'station', 'fail', 'pour', 'clip', 'faulty', 'mindless', 'baby', 'salty', 'truthful', 'mist', 'meat',
             'plot', 'jar', 'travel', 'curious', 'afternoon', 'kick', 'bounce', 'overflow', 'reminiscent', 'list',
             'overconfident', 'optimal', 'humdrum', 'sleet', 'shiny', 'chess', 'unknown', 'chin', 'order', 'abstracted',
             'scandalous', 'pest', 'voyage', 'market', 'rinse', 'black-and-white', 'kittens', 'impartial', 'choke',
             'three', 'x-ray', 'collect', 'escape', 'start', 'colossal', 'march', 'coal', 'vacuous', 'uneven', 'damp',
             'retire', 'noisy', 'step', 'command', 'wrestle', 'piquant', 'hilarious', 'prevent', 'drunk', 'border',
             'fair', 'flat', 'bizarre', 'call', 'guitar', 'eager', 'canvas', 'certain', 'queen', 'tease', 'way', 'team',
             'hang', 'intelligent', 'bump', 'famous', 'precede', 'cause', 'needless', 'ugly', 'dreary', 'aquatic',
             'receptive', 'steer', 'chicken', 'tested', 'ruthless', 'month', 'abusive', 'dinner', 'psychedelic', 'kind',
             'digestion', 'important', 'middle', 'arch', 'dazzling', 'aloof', 'dysfunctional', 'hospitable',
             'dependent', 'mundane', 'believe', 'fire', 'front', 'yard', 'upbeat', 'throne', 'flavor', 'interrupt',
             'water', 'error', 'table', 'history', 'sleep', 'scarecrow', 'toys', 'peck', 'grab', 'spill', 'rhyme',
             'hook', 'scrub', 'flesh', 'magenta', 'bone', 'grotesque', 'sock', 'cherries', 'snakes', 'corn', 'smart',
             'known', 'bustling', 'ambiguous', 'meal', 'wail', 'wire', 'beautiful', 'correct', 'chunky', 'pick',
             'smash', 'rabid', 'hard-to-find', 'steam', 'army', 'soda', 'nation', 'competition', 'rose', 'dream',
             'boil', 'branch', 'bitter', 'makeshift', 'quiver', 'insidious', 'jagged', 'cluttered', 'tart', 'mom',
             'alarm', 'arrive', 'labored', 'icy', 'argument', 'cross', 'touch', 'homeless', 'frame', 'ambitious',
             'umbrella', 'belief', 'endurable', 'post', 'complain', 'stove', 'ossified', 'thoughtful', 'bucket', 'six',
             'loss', 'confuse', 'various', 'berry', 'monkey', 'push', 'gainful', 'impossible', 'pushy', 'arrest',
             'earn', 'sign', 'pray', 'eminent', 'tranquil', 'night', 'true', 'snake', 'deliver', 'baseball', 'doll',
             'victorious', 'dapper', 'cow', 'beg', 'mere', 'dry', 'oatmeal', 'box', 'road', 'talk', 'mailbox', 'aunt',
             'jazzy', 'avoid', 'consider', 'irritating', 'ad hoc', 'drum', 'sink', 'shelter', 'knit', 'workable',
             'sniff', 'ill', 'range', 'redundant', 'wise', 'view', 'shrug', 'run', 'absorbed', 'float', 'bewildered',
             'heady', 'business', 'zephyr', 'beef', 'possessive', 'cloth', 'tax', 'reason', 'undress', 'high', 'shoe',
             'turkey', 'laborer', 'previous', 'boundless', 'steel', 'uncle', 'waste', 'lowly', 'mute', 'multiply',
             'third', 'disappear', 'degree', 'future', 'grey', 'far', 'plastic', 'credit', 'channel', 'juggle', 'tooth',
             'slimy', 'grease', 'gray', 'follow', 'shaky', 'fanatical', 'tickle', 'bleach', 'helpful', 'silver',
             'route', 'sugar', 'shy', 'paltry', 'popcorn', 'shocking', 'dashing', 'key', 'nappy', 'dizzy', 'kaput',
             'lame', 'bird', 'brother', 'helpless', 'rebel', 'sad', 'wholesale', 'prick', 'company', 'fill',
             'communicate', 'pedal', 'angle', 'town', 'puny', 'nonchalant', 'top', 'unequaled', 'exclusive',
             'quizzical', 'crabby', 'decide', 'opposite', 'afterthought', 'false', 'giraffe', 'wistful', 'tedious',
             'root', 'tempt', 'launch', 'harmony', 'brief', 'friend', 'uninterested', 'house', 'word', 'calculate',
             'rough', 'regret', 'moldy', 'satisfying', 'cub', 'grape', 'clammy', 'saw', 'sweet', 'loaf', 'inconclusive',
             'wipe', 'striped', 'hose', 'pathetic', 'terrible', 'heap', 'delirious', 'glue', 'guarantee', 'possible',
             'funny', 'great', 'appreciate', 'condition', 'door', 'tricky', 'vengeful', 'decision', 'drip', 'hallowed',
             'quiet', 'guess', 'shelf', 'realize', 'fat', 'heavy', 'crayon', 'hideous', 'shut', 'colour', 'gorgeous',
             'sigh', 'interest', 'female', 'outstanding', 'remind', 'language', 'delightful', 'mate', 'ring', 'shiver',
             'bottle', 'supply', 'willing', 'gold', 'black', 'lunch', 'omniscient', 'chilly', 'staking', 'misty',
             'duck', 'lettuce', 'jumpy', 'majestic', 'zesty', 'fuzzy', 'spiky', 'quartz', 'soup', 'milky', 'ultra',
             'driving', 'possess', 'impulse', 'wiggly', 'bruise', 'outgoing', 'miniature', 'test', 'violent', 'ghost',
             'eggnog', 'big', 'approve', 'awesome', 'somber', 'common', 'strange', 'automatic', 'bathe', 'boring',
             'clever', 'trot', 'lace', 'plain', 'righteous', 'toothbrush', 'song', 'placid', 'boat', 'belligerent',
             'detect', 'kindhearted', 'suspect', 'wink', 'offbeat', 'mountain', 'hollow', 'guard', 'equal', 'bless',
             'sisters', 'eggs', 'extra-large', 'mother', 'switch', 'berserk', 'seashore', 'government', 'graceful',
             'soak', 'tent', 'filthy', 'beneficial', 'pig', 'mend', 'sophisticated', 'pollution', 'observation',
             'squeamish', 'star', 'flippant', 'overjoyed', 'roasted', 'flowers', 'hover', 'lovely', 'acoustics',
             'profuse', 'rejoice', 'stupid', 'arrange', 'shallow', 'hurt', 'electric', 'suck', 'unique', 'crook',
             'dust', 'trade', 'invention', 'rifle', 'ten', 'military', 'squealing', 'unruly', 'attractive', 'elastic',
             'parsimonious', 'arithmetic', 'pin', 'whisper', 'stocking', 'doubtful', 'torpid', 'activity', 'delicious',
             'complex', 'tough', 'babies', 'greet', 'elfin', 'quilt', 'bath', 'secretary', 'spotless', 'pink', 'pass',
             'worried', 'cats', 'skip', 'jolly', 'mice', 'red', 'cable', 'quicksand', 'serve', 'splendid', 'picture',
             'beam', 'hour', 'elegant', 'harm', 'knowledgeable', 'heartbreaking', 'judicious', 'adventurous', 'fear',
             'defiant', 'gullible', 'hateful', 'surprise', 'responsible', 'event', 'depressed', 'vase', 'rigid',
             'inquisitive', 'handsome', 'temper', 'boot', 'board', 'include', 'joyous', 'exciting', 'crowded', 'madly',
             'cobweb', 'furtive', 'foregoing']
    word = random.choice(words)

    y = 0

    for x in word:
        print('_')

    life = 7
    score = 0

    while True:

        letter = input('Enter letter: ')

        if letter in word:
            if score == len(word):
                print('well done!')
                break
            else:
                for x in word:
                    if letter == x:
                        print(x.upper())
                        score += 1
                    else:
                        print('_')

        else:
            life -= 1
            print('score: ', score,'life: ', life)
            if life == 0:
                print(word)
                break
            print('Wrong!')


yes_no = input('Want to play Hangman? ')

if yes_no.lower() == 'yes' or yes_no.lower() == 'y':
    print('ok')
    hangman()
elif yes_no.lower() == 'no' or yes_no.lower() == 'n':
    print('By By')
    quit()
